### ISSUE TITLE
object-fit: contain

### ISSUE THREAD

**Issue by MarcDAFrame** [aautio/react-modal-image#36]
I'm having an issue where the zoomed in image has a distorted resolution.

I've rememedied this by including in my css
```css
#react-modal-image-img{
object-fit: contain;
}
```

But I'm wondeirng if there is a better way
